# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('login', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
