# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantic', '0007_auto_20170422_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='https://www.dropbox.com/s/k51ngml8jf4zu2m/webcam-toy-photo4.jpg?dl=0', max_length=30),
        ),
    ]
