# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantic', '0009_auto_20170422_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='https://www.dropbox.com/s/fdu1ee65wsoitia/user-icon.png?dl=1', max_length=30),
        ),
    ]
