# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantic', '0011_user_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_upload',
        ),
    ]
